/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ProdutosIndexImport } from './routes/produtos/index'
import { Route as ProdutosNovoImport } from './routes/produtos/novo'
import { Route as ProdutosIdEditarImport } from './routes/produtos/$id.editar'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProdutosIndexRoute = ProdutosIndexImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRoute,
} as any)

const ProdutosNovoRoute = ProdutosNovoImport.update({
  id: '/produtos/novo',
  path: '/produtos/novo',
  getParentRoute: () => rootRoute,
} as any)

const ProdutosIdEditarRoute = ProdutosIdEditarImport.update({
  id: '/produtos/$id/editar',
  path: '/produtos/$id/editar',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/produtos/novo': {
      id: '/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/produtos/novo'
      preLoaderRoute: typeof ProdutosNovoImport
      parentRoute: typeof rootRoute
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosIndexImport
      parentRoute: typeof rootRoute
    }
    '/produtos/$id/editar': {
      id: '/produtos/$id/editar'
      path: '/produtos/$id/editar'
      fullPath: '/produtos/$id/editar'
      preLoaderRoute: typeof ProdutosIdEditarImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/produtos/novo': typeof ProdutosNovoRoute
  '/produtos': typeof ProdutosIndexRoute
  '/produtos/$id/editar': typeof ProdutosIdEditarRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/produtos/novo': typeof ProdutosNovoRoute
  '/produtos': typeof ProdutosIndexRoute
  '/produtos/$id/editar': typeof ProdutosIdEditarRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/produtos/novo': typeof ProdutosNovoRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/produtos/$id/editar': typeof ProdutosIdEditarRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/produtos/novo'
    | '/produtos'
    | '/produtos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/produtos/novo'
    | '/produtos'
    | '/produtos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/produtos/novo'
    | '/produtos/'
    | '/produtos/$id/editar'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ProdutosNovoRoute: typeof ProdutosNovoRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
  ProdutosIdEditarRoute: typeof ProdutosIdEditarRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ProdutosNovoRoute: ProdutosNovoRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
  ProdutosIdEditarRoute: ProdutosIdEditarRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/about",
        "/login",
        "/produtos/novo",
        "/produtos/",
        "/produtos/$id/editar"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/about": {
      "filePath": "about.jsx"
    },
    "/login": {
      "filePath": "login.jsx"
    },
    "/produtos/novo": {
      "filePath": "produtos/novo.jsx"
    },
    "/produtos/": {
      "filePath": "produtos/index.jsx"
    },
    "/produtos/$id/editar": {
      "filePath": "produtos/$id.editar.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
